spring:
  codec:
    max-in-memory-size: 700KB
  data:
    mongodb:
      uri: mongodb://localhost/test
server:
  error:
    include-message: always
ru:
  wallentos:
    carscratcher:
      encar-host: http://api.encar.com/
      encar-original-link: https://fem.encar.com/cars/detail/
      encar-car-header-info-method: search/car/list/general
      encar-car-vehicle-method: v1/readside/vehicle/
      calculator:
        enable-double-convertation: true
        enable-dynamic-valute-part: true
        dynamic-krw-valute-part-map: '{40000: 1600000 , 100000: 1000000}'
        extra-pay-corea:
          krw: 1600000
          rub: 100000
      exchange-api:
        host-cbr: https://www.cbr-xml-daily.ru/daily_json.js
        host-profinance: https://jq.profinance.ru/html/htmlquotes/q
        host-naver: https://finance.naver.com/marketindex/exchangeDetail.nhn?marketindexCd=FX_USDKRW
        exchange-coefficient: ${COEFFICIENT}

